HTTP/1.0 503 Service Unavailable
Pragma: no-cache
Cache-Control: private, max-age=0, no-cache, no-store
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html>
   <body>
      <h1>503 Service Unavailable</h1>
      <p>Sorry, but the service you requested is unavailable.</p>
   </body>
</html>